### ISSUE TITLE
Notizen: Add a new notice

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#10]
## Value Statement
As a user i want to create notes for my dog that i can delete 

## Description
![Bildschirmfoto 2022-01-14 um 08 38 27 AM](https://user-images.githubusercontent.com/93975531/149469471-cfa9564f-f25b-47b3-b69d-b1c698ec29d3.png)

## Acceptance Criteria
- The user can see the notes
- The user can edit and delete notes

## Complexity
M

## Tasks
- [ ] Create feature branch "notes"
- [ ] Create notes component
- [ ] Create the structure of the component
- [ ] Add styling
