### ISSUE TITLE
Termine: Add a new appointment

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#12]
## Value Statement
As a user I want to create new appointments 

## Description
![Bildschirmfoto 2022-01-17 um 11 13 34 AM](https://user-images.githubusercontent.com/93975531/149750690-56aa070b-8d08-4bdd-a248-bd3ee066f9e5.png)

## Acceptance Criteria
- The user sees the current appointments
- The user can edit and delete the upcoming appointments

## Complexity
M/L

## Tasks
- [x] Create feature branch "new-appointment"
- [x] import new appointment component
- [x] add buttons add,delete, to the section
- [ ] add edit button
- [x] add functions for buttons
- [x] Add styling
