### ISSUE TITLE
Add vaccinations section

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#16]
## Value Statement
As a user I want to check all the important vaccinations

## Description

- Activate and date all administered vaccinations

## Acceptance Criteria
- The user sees the important vaccinations
- The user can check the vaccinations
- The user can enter a date of vaccination

## Complexity
M/L

## Tasks
- [x] Create feature branch "add-vaccination"
- [x] import new appointment component
- [x] add checkboxes to the section
- [ ] add date input fields
- [x] add functions 
- [x] Add styling
