### ISSUE TITLE
add deworming section

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#18]
## Value Statement
As a user I want to check the actually deworming

## Description

- Date the atually deworming 
-  the next appointment in 3 months can be viewed

## Acceptance Criteria
- The user sees infomrations about deworming
- The user can date the actual deworming
- The user can see the next appointment in 3 months 

## Complexity
M/L

## Tasks
- [x] Create feature branch "add-deworming"
- [x] Import new deworming component
- [x] Add text to the section
- [x] Add Image to the section
- [x] Add date input field
- [x] Add functions 
- [x] Add styling
