### ISSUE TITLE
General : add navbar

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#2]
## Value Statement
As a user, i want to have the possibility to navigate through the individual pages

## Description

![Bildschirmfoto 2022-01-10 um 08 33 17 AM](https://user-images.githubusercontent.com/93975531/148731332-ede652b7-aa82-481b-a8a6-e4b73bebb13e.png)

## Acceptance Criteria
- The user can access the different pages by clicking on the icons
- The selected icon should be in a different style than the unselected icons

## Complexity
M/L

## Tasks
- [x] Create feature branch "navbar"
- [x] Create navbar component
- [x] Build the navigation with the icons
- [x] Add the routes
- [x] Add styling
