### ISSUE TITLE
Profil: Add profileform in the profil section

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#3]
## Value Statement
As a user I can create a new profile with dummy image

## Description
![Bildschirmfoto 2022-01-10 um 08 42 47 AM](https://user-images.githubusercontent.com/93975531/148732227-212d5f22-62a3-4887-8520-c4338b26aed0.png)

## Acceptance Criteria
- The user can create a profile for his dog

## Complexity
M

## Tasks
- [x] Create feature branch "add profile"
- [x] Create profile component
- [x] Add Input fields
- [x] Add buttons save and edit
