### ISSUE TITLE
Home: Add title image

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#4]
## Value Statement
As a user, i want to start the app

## Description
![Bildschirmfoto 2022-01-06 um 17 34 46 PM](https://user-images.githubusercontent.com/93975531/148734261-738f12ee-5a51-4ac1-a3ce-66c09728371e.png)

## Acceptance Criteria
- The user can launch the app by clicking on the cover image and will be redirected to the profile page

## Complexity
S

## Tasks
- [x] Add a home component
- [x] create new folder images
- [x] Add the title image
- [x] making the title image clickable
