### ISSUE TITLE
General: Add Header

### ISSUE THREAD

**Issue by Joeynow1101** [Joeynow1101/capstone-project#7]
## Value Statement
As a user I want to see which area I am currently in

## Description
![Bildschirmfoto 2022-01-11 um 11 18 33 AM](https://user-images.githubusercontent.com/93975531/148924578-1148f208-2bf9-488a-a012-26941a31207f.png)

## Acceptance Criteria
- The user has a vusual orientation

## Complexity
S

## Tasks
- [x] Create feature branch "header"
- [x] Create header component
- [x] Create a p tag with props "titleText"
- [x] Add the routes
- [x] Add styling
